feat: add conda alias

diff --git a/source/userhome/zshalias b/source/userhome/zshalias
--- a/source/userhome/zshalias
+++ b/source/userhome/zshalias
@@ -43,9 +43,26 @@ if [[ "$(type -w asdf)" == "asdf: function" ]] {
         printf "\n"
     }
     alias find-asdfplugin=' __ax_asdf_find_plugin '
+}
 
-    [[ -x $(asdf which tokei) ]] && \
-        alias tokei=' tokei --exclude .github --exclude .git --compact --sort code '
+if [[ -x "${HOME}/.anaconda3/bin/conda" ]] {
+    __ax_conda_mount() {
+        export CONDA_AUTO_ACTIVATE_BASE=false
+        __conda_setup="$('${HOME}/.anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
+        if [[ $? -eq 0 ]] {
+            eval "$__conda_setup"
+        } else {
+            if [[ -f "${HOME}/.anaconda3/etc/profile.d/conda.sh" ]] {
+                source "${HOME}/.anaconda3/etc/profile.d/conda.sh"
+            } else {
+                export PATH="/home/axl/.anaconda3/bin:$PATH"
+            }
+        }
+        unset __conda_setup
+    }
+    alias mount-conda=' __ax_conda_mount '
+} else {
+    alias mount-conda=' printf "conda not found\n" '
 }
 
 if [[ -x $(which bat 2> /dev/null) ]] {
@@ -62,7 +79,7 @@ if [[ -x $(which bat 2> /dev/null) ]] {
     alias read-log=' __ax_bat_read_log '
     compdef _tail __ax_bat_read_log
 
-    [[ -x $(which fzf-tmux) ]] && \
+    [[ -x $(which fzf-tmux 2> /dev/null) ]] && \
         alias fzf=' fzf-tmux --height 40% --reverse --preview "bat --color=always {}" '
     man() {
         local __AX_WIDTH="$(( COLUMNS > 93 ? 90 : COLUMNS - 3 ))"
@@ -315,7 +332,7 @@ if [[ -x $(which git 2> /dev/null) ]] {
 
     alias confirm-gituntrackedcache=' git update-index --test-untracked-cache '
     alias set-gituntrackedcache=' git update-index --split-index --untracked-cache '
-    [[ -x $(which parallel) ]] && \
+    [[ -x $(which parallel 2> /dev/null) ]] && \
         alias update-gitrepository=' parallel cd {} ";" pwd ";" git pull ";" git submodule update ";"  echo ::: *(/) '
 }
 
@@ -378,7 +395,7 @@ if [[ -x $(which zfs 2> /dev/null) ]] {
 [[ -x $(which thefuck 2> /dev/null) ]] && eval $(thefuck --alias)
 [[ -x $(which tree 2> /dev/null) ]] && alias tree=' tree -I snap --dirsfirst '
 [[ -x $(which xclip 2> /dev/null) ]] && alias copy-selection=' xclip -selection clipboard '
-
+[[ -x $(which tokei 2> /dev/null) ]] && alias tokei=' tokei --exclude .github --exclude .git --compact --sort code '
 
 alias -s {asc,cs,dart,erl,ex{s},fs,htm{l},java,json,py,rebar,rs,scala,txt,xml}=nvim
 alias -s {pdf,ps}=evince
@@ -395,3 +412,4 @@ alias -g V="| nvim - "
 function ls() {
 	[[ -f ~/.hidden ]] && declare GLOBIGNORE=${GLOBIGNORE}:.*:$(tr '\n' ':' < ~/.hidden) ls "$@"
 }
+
